### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by ainich** [theInfectedDrake/TIDoS-Framework#11]
Traceback (most recent call last):
  File "/opt/tidos-framework/tidos.py", line 14, in <module>
    from tidos_main import *
  File "core/tidos_main.py", line 20, in <module>
    from impo import *
  File "core/impo.py", line 16, in <module>
    from passiveo import *
  File "core/passiveo.py", line 31, in <module>
    from footprint_dup import *
  File "core/footprint_dup.py", line 14, in <module>
    from activeo import *
  File "core/activeo.py", line 31, in <module>
    from cms import *
  File "modules/ActiveRecon/cms.py", line 12, in <module>
    import mechanize
ImportError: No module named mechanize

**Comment by theInfectedDrake** [comment]
Hmm I just forgot the dependency. I am pushing out the code changes right now, in the meantime you can solve this yourself by `pip install mechanize` command.

**Comment by ainich** [comment]
Ah, myp pip is pyhon3 by default

**Comment by ainich** [comment]
dnslib, tldextract, BeautifulSoup
stuck on _mysql

**Comment by theInfectedDrake** [comment]
Sure, I fixed the `mechanize` stuff. I will look to these too! Thank you!

**Comment by theInfectedDrake** [comment]
#12 speaks of the same ImportError. Lets open this up.
