### ISSUE TITLE
[ImportError] No module named _mysql

### ISSUE THREAD

**Issue by henrydogard** [theInfectedDrake/TIDoS-Framework#12]
Hi there,

Thank you for putting all of them together. Unfortunately, I ran into a big bug here-
```
Traceback (most recent call last):
File "/opt/tidos-framework/tidos.py", line 14, in 
from tidos_main import *
File "core/tidos_main.py", line 20, in 
from impo import *
File "core/impo.py", line 16, in 
from passiveo import *
File "core/passiveo.py", line 31, in 
from footprint_dup import *
File "core/footprint_dup.py", line 14, in 
from activeo import *
File "core/activeo.py", line 31, in 
from sqlbrute import *
File "modules/AuxilMods/sqlbrute.py", line 12, in 
import _mysql
ImportError: No module named _mysql
```
Any way to resolve this?

**Comment by theInfectedDrake** [comment]
I had fixed it in #11 , it was due to a dependency error of `mysql-python`. Further, I got the `EnvironmentError` fixed by adding the client-dev of `libmysqlclient-dev`. This error shouldn't come up. Still I will investigate it. But from your side can you confirm by a new clone, that this is still persistent?
