### ISSUE TITLE
problem to execute tidos 

### ISSUE THREAD

**Issue by n1n741** [theInfectedDrake/TIDoS-Framework#13]
WARNING: No route found for IPv6 destination :: (no default route?)
Traceback (most recent call last):
  File "/opt/tidos-framework/tidos.py", line 14, in <module>
    from tidos_main import *
  File "core/tidos_main.py", line 20, in <module>
    from impo import *
  File "core/impo.py", line 28, in <module>
    from webbugs import *
  File "core/webbugs.py", line 28, in <module>
    from mailspoof import *
  File "modules/VulnLysis/MiscBugs/mailspoof.py", line 14, in <module>
    import emailprotectionslib.dmarc as dmarclib
  File "/usr/local/lib/python2.7/dist-packages/emailprotectionslib/dmarc.py", line 4, in <module>
    import tldextract
ImportError: No module named tldextract

what should i do ? 

thanks

**Comment by theInfectedDrake** [comment]
Well you should run the `install` file properly. 
```
./install
```
