### ISSUE TITLE
Initial install

### ISSUE THREAD

**Issue by Pilly170** [theInfectedDrake/TIDoS-Framework#29]
Installed, then when I ran tidos

 `# apt-get install sslyze
Reading package lists... Done
Building dependency tree       
Reading state information... Done
sslyze is already the newest version (0.12-0kali1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

# tidos
Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 13, in <module>
    from core.tidos_main import *
  File "/opt/tidos/core/tidos_main.py", line 35, in <module>
    from core.Enumeration.scanenum import *
  File "/opt/tidos/core/Enumeration/scanenum.py", line 25, in <module>
    from ssltlsscan import *
  File "modules/0x02-Scanning+Enumeration/ssltlsscan.py", line 14, in <module>
    import sslyze
ImportError: No module named sslyze
`

**Comment by theInfectedDrake** [comment]
Try doing a `pip install sslyze` to get the python package of sslyze and if you get some output similar to #28, follow the steps I told there. Should solve your problem.
