### ISSUE TITLE
[Invalid] => ImportError: No module named server_connectivity_tester

### ISSUE THREAD

**Issue by MrHacker46** [theInfectedDrake/TIDoS-Framework#30]
Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 13, in <module>
    from core.tidos_main import *
  File "/opt/tidos/core/tidos_main.py", line 35, in <module>
    from core.Enumeration.scanenum import *
  File "/opt/tidos/core/Enumeration/scanenum.py", line 25, in <module>
    from ssltlsscan import *
  File "modules/0x02-Scanning+Enumeration/ssltlsscan.py", line 21, in <module>
    from sslyze.server_connectivity_tester import ServerConnectivityTester
ImportError: No module named server_connectivity_tester

**Comment by theInfectedDrake** [comment]
This cannot be a valid error. Try uninstalling sslyze and then reinstalling it.

**Comment by theInfectedDrake** [comment]
I'm
