### ISSUE TITLE
WARNING: Failed to execute tcpdump

### ISSUE THREAD

**Issue by zombozo12** [theInfectedDrake/TIDoS-Framework#31]
I was running tidos on debian subsystem, and have this output : 

> WARNING: Failed to execute tcpdump. Check it is installed and in the PATH
Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 13, in <module>
    from core.tidos_main import *
  File "/opt/tidos/core/tidos_main.py", line 36, in <module>
    from core.Vulnlysis.vuln import *
  File "/opt/tidos/core/Vulnlysis/vuln.py", line 16, in <module>
    from core.Vulnlysis.Oth_Bugs.othbugs import *
  File "/opt/tidos/core/Vulnlysis/Oth_Bugs/othbugs.py", line 21, in <module>
    from sqlbrute import *
  File "modules/0x03-Vulnerability+Analysis/0x03-OtherWebBugs/sqlbrute.py", line 11, in <module>
    import _mysql
  File "build/bdist.linux-x86_64/egg/_mysql.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/_mysql.py", line 6, in __bootstrap__
ImportError: /usr/lib/x86_64-linux-gnu/libmariadbclient.so.18: version `libmysqlclient_18' not found (required by /root/.cache/Python-Eggs/MySQL_python-1.2.5-py2.7-linux-x86_64.egg-tmp/_mysql.so)

How to solve this?

**Comment by zombozo12** [comment]
silly me, just need to google a little bit. I found this gem:

`sudo -H pip install --no-binary mysqlclient mysqlclient`

👍

**Comment by zombozo12** [comment]
But still, I have this warning:

> WARNING: Failed to execute tcpdump. Check it is installed and in the PATH

**Comment by theInfectedDrake** [comment]
Okay, so you're running a plaintext credential bruteforcing module which is `sqlbrute`. So make sure you're running this against a server with some sorta SQL service running and accepting logins via plaintext credentials.

And now to the second part, to solve the `tcpdump` error, just install tcpdump via `sudo apt install tcpdump`. I am including that one of my dependencies which I had missed out. 

Thanks for pointing out. 😉
