### ISSUE TITLE
[Invalid] => cant open this tools  in mac OSX 

### ISSUE THREAD

**Issue by ismartSa** [theInfectedDrake/TIDoS-Framework#35]
Traceback (most recent call last):
  File "tidos.py", line 13, in <module>
    from core.tidos_main import *
  File "/Users/iSmartSa/tidos-framework/core/tidos_main.py", line 31, in <module>
    from core.Auxillaries.auxil import *
  File "/Users/iSmartSa/tidos-framework/core/Auxillaries/auxil.py", line 23, in <module>
    from imgext import *
  File "modules/0x05-Auxillaries+PF6/imgext.py", line 13, in <module>
    import PIL.ExifTags
ImportError: No module named PIL.ExifTags

**Comment by theInfectedDrake** [comment]
TIDoS is built on Python 2.x, so make a confirmation that you're defaulting on Python 2.x version. Try installing the `pillow` module via `pip2 install pillow` and try again. 🙂

**Comment by ismartSa** [comment]
think you i will try now .
