### ISSUE TITLE
IndexError: List Index out of Range

### ISSUE THREAD

**Issue by KelvinSantaigo** [theInfectedDrake/TIDoS-Framework#9]
Hi there,

I ran into an exception inspite of the `global error handling feature`. I was running the `iphistory` module under `PassiveRecon`. However the error came up like this:
```
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
File "/opt/TIDoS/modules/PassiveRecon/iphistory.py", line 62, in run
File "/usr/lib/python2.7/Queue.py", line 168, in get
File "/usr/lib/python2.7/threading.py", line 333, in wait
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
```
Any idea on how this is happening and how it can be resolved?

Thanks,

**Comment by theInfectedDrake** [comment]
Hmm seems like the argument length exceeded the parameter length. I will look to it. Thank you!
